# Site settings
title: Johan Ask
email: jhnesk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Nothing yet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jhnesk.github.io" # the base hostname & protocol for your site
github_username: jhnesk

# Build settings
markdown: kramdown
